export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const REMOVE_ITEM_COMPLETELY = 'REMOVE_ITEM_COMPLETELY';
export const CLEAR_CART = 'CLEAR_CART';

export const INIT_GUITARS = 'INIT_GUITARS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const INIT_USER_DETAILS = 'INIT_USER_DETAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const INIT_ORDERS = 'INIT_ORDERS';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
